config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'posts#index'
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end

  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :content, presence: true, length: { minimum: 2, maximum: 300 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :image, presence: true
  validates :user_id, presence: true
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "150x150#" }, default_url: "/app/images/missing.png"

  validates :username, presence: true, length: { minimum: 4, maximum: 18 }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:show, :destroy]

  def index
    @comments = Comment.all
  end

  def show

  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.js
      end
    else
      flash[:alert] = "Check the comment form, something went horribly wrong."
      render root_path
    end
  end

  def destroy
    if @comment.user_id = current_user.id
      if @comment.destroy
        respond_to do |format|
          format.html { redirect_to posts_path }
          format.js
        end
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :owns_post, only: [:edit, :update, :destroy]


  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been published!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your post could not be created. Please check the form"
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post successfully updated."
      redirect_to post_path(@post)
    else
      flash[:error] = "Couldn't updated post at this time."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def like
    @post.liked_by current_user
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end
  end


  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owns_post
    unless @post.user == current_user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to posts_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :get_user, only: [:show, :edit, :update]

  def show
    unless @user
      flash[:alert] = "User not found"
      redirect_to posts_path
    else
      @posts = @user.posts.order("created_at DESC").page(params[:page]).per(6)
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated!"
    else
      flash[:error] = "Couldn't update..."
    end
    redirect_to edit_profile_path
  end

  private

  def user_params
    params.require(:user).permit(:bio, :avatar)
  end

  def get_user
    username = params[:username].downcase
    @user = User.where('lower(username) = ?', username).first
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Bootstrap flash alert styles
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/monkeys_helper.rb
module MonkeysHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.slim
p id="comment_#{comment.id}"
  strong>= comment.user.username
  = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, remote: true, data: { confirm: "Are you sure?"}, class: "pull-right"
      i.icon.ion-close

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/layouts/_footer.html.slim
- if user_signed_in?
    nav.navbar.navbar-inverse.navbar-fixed-bottom
      .container
        .navbar-header
          = link_to "#{current_user.username}", profile_path(current_user.username), class: 'navbar-brand'

app/views/layouts/_nav.html.slim
nav.navbar.navbar-default
  .container-fluid.navbar-container
    .navbar-header
      button.navbar-toggle.collapsed data-target = "#bs-navbar-collapse-1" data-toggle = "collapse" type = "button"
        span.sr-only Toggle Navigation
        span.icon-bar
        span.icon-bar
      .navbar-brand= link_to "Instagram", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li style="font-weight:bold;"
            = link_to current_user.username, profile_path(current_user.username)
          li
            = link_to "Upload", new_post_path
          li
            = link_to "Logout (#{current_user.username})", destroy_user_session_path, method: :delete
        - else
          li
            = link_to "Login", '#'
          li
            = link_to "Register", '#'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Instagram
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/nav'

    #main_container.container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: [:alert, alert_for(name)]
      = yield

    = render 'layouts/footer'

app/views/posts/_form.html.slim
h1 Form

= simple_form_for @post do |f|
  = f.input :caption, label: 'Enter a caption', error: 'Caption is mandatory, please specify one'
  = f.input :image

  br
  = f.button :submit

app/views/posts/_likes.html.slim
= content_tag :span, post.votes_for.size, id: "vote_count-#{post.id}"

app/views/posts/_post.html.slim
div.row
  div.col-xs-12.col-sm-6.col-sm-offset-3
    div.thumbnail.post style="padding:0;"
      div.caption style="padding-bottom: 10px;"
        strong.pull-left= link_to post.user.username, profile_path(post.user.username)
        .date.pull-right= time_ago_in_words(post.created_at) + " ago"
        span.clearfix
      = link_to (image_tag post.image.url(:medium), class: 'img-responsive'), post_path(post)
      div.caption
        p
          = link_to raw('<i class="icon ion-heart"></i>'), like_post_path(post), remote: true, class: "btn"
          = render 'posts/likes', post: post

        p= post.caption

        .comments id="comments_#{post.id}"
          - if post.comments
            = render post.comments, post: post
        .comment-form
          = form_for([post, post.comments.new], remote: true) do |f|
            i.icon.ion-chatbox.float-left
            = f.text_field :content, placeholder: 'Add a comment...', id: "comment_content_#{post.id}", :maxlength => 300

app/views/posts/edit.html.slim
.text-center
  = image_tag @post.image.url(:medium)
=render 'form'

app/views/posts/index.html.slim
-@posts.each do |post|
  = render "post", post: post

.text-center.center-block= paginate @posts

app/views/posts/like.js.erb
$("#vote_count-<%= @post.id %>").html(<%=j @post.votes_for.size %>)

app/views/posts/new.html.slim
=render 'form'

app/views/posts/show.html.slim
= link_to 'Back', posts_path
= render "post", post: @post

div.center-block.text-center
  -if @post.user.id == current_user.id
    p.btn-group
      = link_to 'Edit', edit_post_path(@post), class: 'btn btn-default'
      = link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'

app/views/profiles/edit.html.slim
.container
  .row
    = link_to "Back", profile_path(@user.username)

  .row
    h1 = "Update profile for #{@user.username}"

  = simple_form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
    .row
      .form-group
        h4 Change your profile image:
        .img-circle
          = image_tag @user.avatar.url(:thumb), class: "img-circle"
        = f.file_field :avatar, onChange: 'loadFile(event)'

    .row
      .form-group
        h4 Update your bio:
        = f.text_area :bio, label: false, rows: 4, class: "form-control"

    .row
      = f.button :submit

app/views/profiles/show.html.slim
.row
  .container
    - if @user.avatar.exists?
      .div.pull-left.avatar_holder
        = image_tag @user.avatar.url(:thumb), class: "img-circle"

    .div.pull-left
      h1 = @user.username
      h4 = @user.bio
      - if @user == current_user
        = link_to "Edit Profile", edit_profile_path

.user_posts
  -@posts.in_groups_of(3) do |group|
    .row
      -group.each do |post|
        - if post
          div.col-md-4
            .thumbnail
              .img-holder
                = link_to (image_tag post.image.url(:medium), class: "img-reponsive"), post_path(post)
              div.caption
                = post.caption
                - if post.comments.count > 0
                  span.pull-right
                    i.icon.ion-chatbox
                    = " #{post.comments.count}"

.text-center.center-block = paginate @posts